// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miiy/goc-quickstart/nova-gateway/internal/app"
	"github.com/miiy/goc-quickstart/nova-gateway/internal/config"
	"github.com/miiy/goc/logger"
)

// Injectors from wire.go:

func InitApp(conf string) (*app.App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	v := provideLoggerOption()
	logger, cleanup, err := provideLogger(v)
	if err != nil {
		return nil, nil, err
	}
	appApp, cleanup2, err := app.NewApp(configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideLoggerOption() []logger.Option {
	return nil
}

func provideLogger(options []logger.Option) (logger.Logger, func(), error) {
	l, err := logger.NewLogger(options...)
	if err != nil {
		return nil, nil, err
	}
	return l, func() {
		if sync, ok := l.(interface{ Sync() error }); ok {
			_ = sync.Sync()
		}
	}, nil
}
