### healthz
GET http://localhost:8080/healthz
Accept: application/json

### echo get
GET http://localhost:8080/api/v1/echo
Accept: application/json


### echo get id
GET http://localhost:8080/api/v1/echo/2
Accept: application/json

### echo get post
POST http://localhost:8080/api/v1/echo
Accept: application/json

{
    "id": 3,
    "user_name": "test2"
}

### echo error
GET http://localhost:8080/api/v1/echo-error
Accept: application/json

### file upload
POST http://localhost:8080/api/v1/file/upload
Accept: application/json

### healthz
GET http://localhost:8080/healthz
Accept: application/json

### healthz service
GET http://localhost:8080/healthz?service=echo
Accept: application/json


### auth login
POST http://localhost:8080/api/v1/auth/login
Accept: application/json

###
