// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miiy/goc-quickstart/nova-web/client"
	"github.com/miiy/goc-quickstart/nova-web/internal/app"
	"github.com/miiy/goc-quickstart/nova-web/internal/config"
	"github.com/miiy/goc-quickstart/nova-web/internal/module"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/auth"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/post"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/user"
	"github.com/miiy/goc-quickstart/nova-web/internal/session"
	"github.com/miiy/goc/gin/sessions"
	"github.com/miiy/goc/logger"
	"net/http"
)

// Injectors from wire.go:

func InitApp(conf string) (*app.App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	v := provideLoggerOption()
	loggerLogger, err := logger.NewLogger(v...)
	if err != nil {
		return nil, nil, err
	}
	clients, cleanup, err := provideClients(configConfig)
	if err != nil {
		return nil, nil, err
	}
	options := provideSessionOptions(configConfig)
	store, err := provideSessionStore(configConfig, options)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	manager := provideSessionManager(store, configConfig)
	postClient := providePostClient(clients)
	authClient := provideAuthClient(clients)
	userClient := provideUserClient(clients)
	fileClient := provideFileClient(clients)
	modules := provideModules(loggerLogger, postClient, authClient, userClient, fileClient, manager)
	appApp := app.NewApp(configConfig, loggerLogger, clients, manager, modules)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideLoggerOption() []logger.Option {
	return nil
}

func provideClients(config2 *config.Config) (*client.Clients, func(), error) {
	return client.NewClients(config2.Gateway.Addr)
}

func providePostClient(clients *client.Clients) *client.PostClient {
	return clients.Post
}

func provideAuthClient(clients *client.Clients) *client.AuthClient {
	return clients.Auth
}

func provideUserClient(clients *client.Clients) *client.UserClient {
	return clients.User
}

func provideFileClient(clients *client.Clients) *client.FileClient {
	return clients.File
}

func provideSessionOptions(config2 *config.Config) sessions.Options {
	return sessions.Options{
		Path:     "/",
		MaxAge:   config2.Session.MaxAge,
		Secure:   config2.Session.Secure,
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
	}
}

func provideSessionStore(config2 *config.Config, options sessions.Options) (sessions.Store, error) {
	store, err := sessions.NewRedisStore(10, "tcp", config2.Redis.Addr, config2.Redis.Password, []byte(config2.Session.Secret))
	if err != nil {
		return nil, err
	}
	if err := sessions.UseJSONSerializer(store); err != nil {
		return nil, err
	}
	store.Options(options)
	if config2.Session.MaxAge > 0 {
		if err := sessions.SetMaxAge(store, config2.Session.MaxAge); err != nil {
			return nil, err
		}
	}
	return store, nil
}

func provideSessionManager(store sessions.Store, config2 *config.Config) *session.Manager {
	return session.NewManager(store, config2.Session.Name)
}

func provideModules(
	log logger.Logger,
	postClient *client.PostClient,
	authClient *client.AuthClient,
	userClient *client.UserClient,
	fileClient *client.FileClient,
	sessionManager *session.Manager,
) *module.Modules {
	return &module.Modules{
		Post: post.NewModule(log, postClient, fileClient, sessionManager),
		Auth: auth.NewModule(log, authClient, sessionManager),
		User: user.NewModule(log, authClient, userClient, fileClient, sessionManager),
	}
}
