// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miiy/goc-quickstart/nova-web/gen/go/nova/auth/v1"
	"github.com/miiy/goc-quickstart/nova-web/gen/go/nova/post/v1"
	"github.com/miiy/goc-quickstart/nova-web/gen/go/nova/user/v1"
	"github.com/miiy/goc-quickstart/nova-web/internal/app"
	"github.com/miiy/goc-quickstart/nova-web/internal/client"
	"github.com/miiy/goc-quickstart/nova-web/internal/config"
	"github.com/miiy/goc-quickstart/nova-web/internal/module"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/auth"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/post"
	"github.com/miiy/goc-quickstart/nova-web/internal/module/user"
	"github.com/miiy/goc-quickstart/nova-web/internal/session"
	"github.com/miiy/goc/gin/sessions"
	"github.com/miiy/goc/logger"
	"net/http"
)

// Injectors from wire.go:

func InitApp(conf string) (*app.App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	v := provideLoggerOption()
	loggerLogger, err := logger.NewLogger(v...)
	if err != nil {
		return nil, nil, err
	}
	clients, cleanup, err := provideClients(configConfig)
	if err != nil {
		return nil, nil, err
	}
	options := provideSessionOptions(configConfig)
	store, err := provideSessionStore(configConfig, options)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	manager := provideSessionManager(store, configConfig)
	postServiceClient := providePostService(clients)
	authServiceClient := provideAuthService(clients)
	userServiceClient := provideUserService(clients)
	modules := provideModules(configConfig, loggerLogger, postServiceClient, authServiceClient, userServiceClient, manager)
	appApp := app.NewApp(configConfig, loggerLogger, clients, manager, modules)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideLoggerOption() []logger.Option {
	return nil
}

func provideClients(config2 *config.Config) (*client.Clients, func(), error) {
	return client.NewClients(config2)
}

func providePostService(clients *client.Clients) postv1.PostServiceClient {
	return clients.Post
}

func provideAuthService(clients *client.Clients) authv1.AuthServiceClient {
	return clients.Auth
}

func provideUserService(clients *client.Clients) userv1.UserServiceClient {
	return clients.User
}

func provideSessionOptions(config2 *config.Config) sessions.Options {
	return sessions.Options{
		Path:     "/",
		Domain:   config2.Session.Domain,
		MaxAge:   config2.Session.MaxAge,
		Secure:   config2.Session.Secure,
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
	}
}

func provideSessionStore(config2 *config.Config, options sessions.Options) (sessions.Store, error) {
	store, err := sessions.NewRedisStore(10, "tcp", config2.Redis.Addr, config2.Redis.Password, []byte(config2.Session.Secret))
	if err != nil {
		return nil, err
	}
	if err := sessions.UseJSONSerializer(store); err != nil {
		return nil, err
	}
	store.Options(options)
	if config2.Session.MaxAge > 0 {
		if err := sessions.SetMaxAge(store, config2.Session.MaxAge); err != nil {
			return nil, err
		}
	}
	return store, nil
}

func provideSessionManager(store sessions.Store, config2 *config.Config) *session.Manager {
	return session.NewManager(store, config2.Session.Name, provideSessionOptions(config2))
}

func provideModules(
	cfg *config.Config,
	log logger.Logger,
	postClient postv1.PostServiceClient,
	authClient authv1.AuthServiceClient,
	userClient userv1.UserServiceClient,
	sessionManager *session.Manager,
) *module.Modules {
	return &module.Modules{
		Post: post.NewModule(postClient, userClient),
		Auth: auth.NewModule(log, authClient, sessionManager, cfg.App.RegisterEnabled),
		User: user.NewModule(userClient, sessionManager),
	}
}
