// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"net/http"

	"github.com/miiy/goc-quickstart/nova-web/client"
	"github.com/miiy/goc-quickstart/nova-web/internal/app"
	"github.com/miiy/goc-quickstart/nova-web/internal/config"
	"github.com/miiy/goc/gin/sessions"
	"github.com/miiy/goc/logger"
)

// Injectors from wire.go:

func InitApp(conf string) (*app.App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	v := provideLoggerOption()
	loggerLogger, err := logger.NewLogger(v...)
	if err != nil {
		return nil, nil, err
	}
	clients, cleanup, err := provideClients(configConfig)
	if err != nil {
		return nil, nil, err
	}
	v2 := provideSessionOptions(configConfig)
	v3, err := provideSessionStore(configConfig, v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appApp := app.NewApp(configConfig, loggerLogger, clients, v3)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideLoggerOption() []logger.Option {
	return nil
}

func provideClients(config2 *config.Config) (*client.Clients, func(), error) {
	return client.NewClients(config2.Gateway.Addr)
}

func provideSessionOptions(config2 *config.Config) sessions.Options {
	return sessions.Options{
		Path:     "/",
		MaxAge:   config2.Session.MaxAge,
		Secure:   config2.Session.Secure,
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
	}
}

func provideSessionStore(config2 *config.Config, options sessions.Options) (sessions.Store, error) {
	store, err := sessions.NewRedisStore(10, "tcp", config2.Redis.Addr, config2.Redis.Password, []byte(config2.Session.Secret))
	if err != nil {
		return nil, err
	}
	if err := sessions.UseJSONSerializer(store); err != nil {
		return nil, err
	}
	store.Options(options)
	if config2.Session.MaxAge > 0 {
		if err := sessions.SetMaxAge(store, config2.Session.MaxAge); err != nil {
			return nil, err
		}
	}
	return store, nil
}
